swagger: '2.0'
info:
  description: BOTcall
  version: 1.0.0
  title: BOTcall
  contact:
    email: afioritto@casacurait
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: '10.4.2.229:3000'
basePath: /
consumes:
  - application/json
produces:
  - application/json
paths:
  /iibbpm:
    put:
      operationId: sendMSG
      responses:
        '200':
          description: message received
      parameters:
        - name: msg
          in: body
          description: json format for the message
          schema:
            $ref: '#/definitions/iibbpm'
definitions:
  iibbpm:
    type: object
    properties:
      from:
        type: string
      to:
        type: string
      status:
        type: string
      msg:
        type: string
      type:
        type: string
      token:
        type: string
